# Generated by Django 4.1.7 on 2023-03-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvauser',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
