type: docker
kind: pipeline
name: test and deploy

steps:
  - name: django-tests
    image: python:3.9-slim-buster
    commands:
      - pip install minio
      - python ci-cd/set_up_buckets.py
      - pip install -r requirements.txt
      - python manage.py test
    environment:
      DEBUG: false
      DB_NAME: test_db
      DB_USERNAME: root
      DB_HOST: database
      DB_PASSWORD: TestPassword
      SECRET_KEY: TEST_SECRET_KEY
      HASHID_FIELD_SALT: TEST_HASHID_SALT
    failure: ignore  # @todo remove this when ready for first release
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      repo: registry.sliceofbits.com/pixellemonade
      registry: registry.sliceofbits.com/
      tags: latest
    when:
      branch:
        - dev # @todo set to main when ready for first release
      event:
        - push

services:
  - name: database
    image: postgres:14-alpine
    ports:
    - 5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: TestPassword
      POSTGRES_USER: root
  - name: s3
    image: minio
    ports:
      - 5432
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command:
      - server /data"