version: '2'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: pass # set a password for the database
      POSTGRES_USER: root # set the username for the database
      POSTGRES_DB: pixellemonade # give the default database a name
    volumes:
      - ./db-data:/var/lib/postgresql/data # mount the data folder to a local folder named "db-data" this makes is easyer to update the database
    ports:
      - 5432:5432 #expose the port, so you can access the port with a database management programm
    networks:
      - backend

  s3:
    image: minio/minio:latest
    command: server /data --console-address "0.0.0.0:9002"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9002:9002"
    networks:
      - backend
    volumes:
      - ./s3-data:/data

  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=rabbitpassword
    ports:
      - 8080:8080
      - 5672:5672
      - 15672:15672
    networks:
      - backend

networks:
  backend:
    external: false