# Generated by Django 4.1.7 on 2023-04-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uploader_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodownload',
            name='session',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='photoview',
            name='session',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
