# Generated by Django 4.1.7 on 2023-05-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_photodownload_session_photoview_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photodownload',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='photoview',
            name='browser',
        ),
    ]
