# Generated by Django 4.1.7 on 2023-06-02 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_photographer_delete_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
