# Generated by Django 4.1.7 on 2023-06-02 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_photographer_profile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='copyright_match',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
