# Generated by Django 4.1.7 on 2023-06-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_photographer_copyright_match_alter_photographer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.photographer'),
        ),
    ]
