# Generated by Django 4.1.7 on 2023-06-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_photo_photographer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='copyright_match',
        ),
    ]
