# Generated by Django 4.1.7 on 2023-06-02 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_photographer_copyright_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='copyright_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
    ]
