# Generated by Django 4.2.5 on 2023-10-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_photographer_copyright_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='in_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.album'),
        ),
    ]
