# Generated by Django 4.1.7 on 2023-03-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_photoview_photodownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodigi_id', models.CharField(max_length=30)),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('shipping_method', models.CharField(max_length=20)),
                ('status', models.JSONField()),
                ('charges', models.JSONField()),
                ('shipments', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('address_postal_or_zip_code', models.CharField(max_length=50)),
                ('address_country_code', models.CharField(max_length=50)),
                ('address_town_or_city', models.CharField(max_length=200)),
                ('address_state_or_country', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=None, max_length=30)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('product_dimensions_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product_dimensions_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product_dimensions_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('of_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='prodigi.productgroup')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('sizing', models.CharField(choices=[('fillPrintArea', 'fillPrintArea'), ('fitPrintArea', 'fitPrintArea'), ('stretchToPrintArea', 'stretchToPrintArea')], max_length=20)),
                ('recipientCost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attributes', models.JSONField()),
                ('of_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prodigi.order')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.photo')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prodigi.recipient'),
        ),
    ]
