# Generated by Django 4.1.7 on 2023-03-29 21:13

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('prodigi', '0004_product_name_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcard',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=6, prefix='', primary_key=True, serialize=False),
        ),
    ]
